# This task gets all Junos configuration from all devices
- name: Build and deploy configuration
  hosts: fabric
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  tasks:
    - name: Deploy config to device ... please wait
      junos_install_config:
        host: "{{ ansible_ssh_host }}"
        port: "{{ ansible_ssh_port }}"
        user: root
        passwd: Juniper
        file: "./config/{{ inventory_hostname }}.conf"
        overwrite: yes
        replace: no
