# This task gets all Junos configuration from all devices
---
- name: Get facts
  hosts: fabric
  connection: local                       # code is run locally
  gather_facts: no                        # don't gather facts
  tasks:
    - name: get facts from device
      napalm_get_facts:                   # NAPALM plugin
        hostname: "{{ ansible_ssh_host }}"            # start of connection parameters
        username: "root"
        password: "Juniper"
        dev_os: "{{ os }}"
        optional_args:
          port: "{{ ansible_ssh_port }}"             # end of connection parameters
        filter: ['mac_address_table']                # which NAPALM getters to use
      register: napalm_facts             # store information here
      tags: [print_action]
    - name: Print gathered facts
      debug:
        msg: "{{ napalm_facts.ansible_facts | to_nice_json }}"
      tags: [print_action]
