---
- name: Validate
  hosts: fabric
  connection: local
  gather_facts: no
  tasks:
  - name: "prepate tmp"
    file: path=./tmp state=directory
  - name: include cabling vars
    include_vars: ./cabling_vars/{{ inventory_hostname }}.yaml
  - name: "Generate validation rules"
    template:
      src: "./templates/validate/lldp.j2"
      dest: "./tmp/{{ inventory_hostname }}.yaml"
    changed_when: no
    check_mode: no
  - name: "Read validation rules, gather data and verify it against rules"
    ignore_errors: yes
    napalm_validate:
      hostname: "{{ ansible_ssh_host }}"
      username: "root"
      dev_os: "{{ os }}"
      password: "Juniper"
      optional_args:
        port: "{{ ansible_ssh_port }}"
      validation_file: "./tmp/{{ inventory_hostname }}.yaml"
    register: validation
  - name: "Failed report"
    debug:
      msg: "{{ validation.compliance_report|to_nice_json }}"
    when: not validation.compliance_report.complies
    tags: [print_action]
  - name: "Failed Compliance Report prepare"
    file: path=./reports/tmp state=directory
  - name: "Failed Compliance Report prepare"
    file: path=./reports/lldp.report state=absent
  - name: "Failed Compliance Report save"
    copy:
      dest: ./reports/tmp/{{ inventory_hostname }}.report
      content: |
        =====
        {{ inventory_hostname }} PORTS
        {% for name,state in validation.compliance_report.get_lldp_neighbors.present.items() %}
        {% if not state.complies %}
        ----
        NEIGHBOR {{ state.actual_value[0].hostname }} PORT {{ state.actual_value[0].port }}
        TO DEVICE_CHECK {% if state.actual_value[0].hostname == state.expected_value[0].hostname %} OK {% else %} FAIL
        {% endif %}
        TO PORT_CHECK {% if state.actual_value[0].port == state.expected_value[0].port %} OK {% else %} FAIL
        {% endif %}
        SHOULD BE NEIGHBOR {{ state.expected_value[0].hostname }} PORT {{ state.expected_value[0].port }}
        ----
        {% endif %}
        {% endfor %}
        =====
    delegate_to: localhost
    when: not validation.compliance_report.complies
  - name: "Failed Compliance Report save"
    assemble:
      src: ./reports/tmp/
      dest: ./reports/lldp.report
  - name: "delete files"
    file: path=./reports/tmp/{{ inventory_hostname }}.report state=absent
  - name: 'delete files'
    file: path=./tmp/{{ inventory_hostname }}.yaml state=absent
  - name: "Failed Compliance Report"
    fail:
      msg: "{{ validation.compliance_report|to_nice_json }}"
    when: not validation.compliance_report.complies
  - name: "Compliance report"
    debug:
      msg: "Complies"
    when: validation.compliance_report.complies
    tags: [print_action]
