---
# handlers file for esxi-installer
- name: restart dhcp
  service:
   name: dhcpd
   state: restarted
- name: restart tftp
  service:
   name: "{{ item }}"
   state: restarted
  with_items:
   - xinetd
   - tftp
