vlans:
  - layer: layer3
    type: interconnect
    ip_number: 1
    service_groups:
      - svc-c
  - layer: layer3
    type: interconnect
    ip_number: 1
    vlans:
      - i-leaf-exit01
  - layer: layer2
    type: service
    service_groups:
      - dmz
unit_id: 5
aggregated_ports:
  ae01: ['xe-0/0/0','xe-0/0/1']
interconnects:
  ae01: i-leaf-exit01
trunk_ports:
  - service_groups:
      - dmz
    ports:
     - xe-0/0/3
  - service_groups:
      - svc-c
    ports:
      - xe-0/0/4
  - ports:
     - ae01
