vlans:
 - layer: layer3
   ip_number: 1
   type: service
   vlan_list:
    - un-mgmt-esxi02
    - un-mgmt-vmotion02
    - un-mgmt-vsan02
    - vtep-mgmt02
    - stor-nfs02
 - layer: layer3
   ip_number: 2
   type: interconnect
   vlan_list:
    - i-leaf-exit01
loopback_id: 4
ports:
  fabric_ports:
    - xe-0/0/0
    - xe-0/0/2
    - xe-0/0/1
    - xe-0/0/3
  aggregated_ports:
    ae01: ['xe-0/0/5','xe-0/0/6']
  access_ports:
    - vlan: stor-nfs02
      ports:
       - xe-0/0/4
  trunk_ports:
   - vlans: [i-leaf-exit01]
     ports:
      - ae01
