underlay_id: '01'

vlans:
  - layer: layer3
    ip_number: 1
    type: service
    service_groups:
     - mgmt_underlay

unit_id: 3
fabric_ports:
  - xe-0/0/0
  - xe-0/0/1
trunk_ports:
  - service_groups:
      - mgmt_underlay
    ports:
     - xe-0/0/2
