vlans:
  - layer: layer3
    ip_number: 1
    type: service
    vlan_list:
     - un-mgmt-esxi01
     - un-mgmt-vmotion01
     - un-mgmt-vsan01
     - vtep-mgmt01
     - stor-nfs01

loopback_id: 3
ports:
  fabric_ports:
    - xe-0/0/0
    - xe-0/0/1
  access_ports:
    - vlan: stor-nfs01
      ports:
       - xe-0/0/2
    
