vlans:
  layer3:
    storages:
      stor-nfs02: 1

fabric_ports:
  - xe-0/0/0
  - xe-0/0/2
  - xe-0/0/1
  - xe-0/0/3
id: 4
ports:
  fabric_ports:
    - xe-0/0/0
    - xe-0/0/2
    - xe-0/0/1
    - xe-0/0/3
  single_ports:
    access_ports:
      - { name: xe-0/0/4, group: storages, vlan: stor-nfs02 }
