underlay_id: '02'
vlans:
  - layer: layer3
    ip_number: 1
    type: service
    service_groups:
     - mgmt_underlay
  - layer: layer3
    type: interconnect
    ip_number: 2
    vlans:
      - i-leaf-exit01

unit_id: 3

interconnects:
  ae01: i-leaf-exit01
aggregated_ports:
  ae01: ['xe-0/0/2','xe-0/0/3']
trunk_ports:
  - service_groups:
      - mgmt_underlay
    ports:
     - xe-0/0/2
  - ports: ['ae01']
