- name: fabric_interfaces
  blockinfile:
    path: ./config/{{inventory_hostname}}.conf
    marker: ""
    block: |
     {% if ospf_enabled %}
      ospf {
          area {{ ospf_area }} {

              interface lo0.0 {
                  passive;
              }
        {% if fabric_ports is defined %}
        {% for port in fabric_ports %}
              interface {{port}}.0 {
                  interface-type p2p;
              }
        {% endfor %}
        {% endif %}
        {% if vlans is defined %}
        {% for vlan_group in vlans %}
        {% if vlan_group['layer'] in ['layer3'] %}
        {% if vlan_group['vlans'] is defined %}
        {% for vlan_name in vlan_group['vlans'] %}
         interface {{ vlanif_definition }}.{{ network_db[vlan_name]['vlan'] }} {
           {% if vlan_group.ospf_passive is defined %}
               passive;
           {% else %}
                interface-type p2p;
           {% endif %}
                  }

        {% endfor %}
        {% endif %}
        {% if vlan_group['service_groups'] is defined %}
        {% for local_service_group in vlan_group['service_groups'] %}
        {% for vlan_name in service_groups[local_service_group]['networks'] %}
        {% set vlan_name = vlan_name+underlay_id  if service_groups[local_service_group]['type'] == 'underlay' else vlan_name %}
          interface {{ vlanif_definition }}.{{ network_db[vlan_name]['vlan'] }} {
            {% if vlan_group.ospf_passive is defined %}
                passive;
            {% else %}
                 interface-type p2p;
            {% endif %}
                   }
        {% endfor %}
        {% endfor %}
        {% endif %}
        {% endif %}
        {% endfor %}
        {% endif %}

          }
        }
      {% endif %}
