

- name: vlanif interfaces
  blockinfile:
    path: ./config/{{inventory_hostname}}.conf
    marker: ""
    block: |
         {% if vlans is defined %}
         {% set layer_list = vlans | map(attribute='layer') %}
         {% if 'layer3' in layer_list %}
         {{ vlanif_definition }} {
         {% for vlan_group in vlans %}
         {% if vlan_group['layer'] in ['layer3'] %}
         {% set ip = vlan_group['ip_number'] %}
         {% if vlan_group['vlans'] is defined %}
         {% for vlan_name in vlan_group['vlans'] %}
         unit {{ network_db[vlan_name]['vlan'] }}{
           description {{ vlan_name }};
           family inet {

             address {{ network_db[vlan_name]['net'] | ipaddr(ip) }};

             }
         }
         {% endfor %}
         {% endif %}
         {% if vlan_group['service_groups'] is defined %}
         {% for local_service_group in vlan_group['service_groups'] %}
         {% for vlan_name in service_groups[local_service_group]['networks'] %}
         {% set vlan_name = vlan_name+underlay_id  if service_groups[local_service_group]['type'] == 'underlay' else vlan_name %}
           unit {{ network_db[vlan_name]['vlan'] }}{
             description {{ vlan_name }};
             family inet {
               address {{ network_db[vlan_name]['net'] | ipaddr(ip) }};
               }
           }
         {% endfor %}
         {% endfor %}
         {% endif %}
         {% endif %}
         {% endfor %}
          }
         {% endif %}
         {% endif %}
