

- name: switchports
  blockinfile:
    path: ./config/{{inventory_hostname}}.conf
    marker: ""
    block: |
       {% if access_ports is defined %}
       {% for port_group in access_ports %}
       {% for port in port_group.ports %}
         {{ port }} {
           {% if 'ae' in port %}
           aggregated-ether-options lacp active;
           {% endif %}
               unit 0 {
           family ethernet-switching {
            {{ switchport_pattern }} access;
            vlan {
              members {{ port_group.vlan }};
            }
           }
         }
       }
       {% endfor %}
       {% endfor %}
       {% endif %}
       {% if trunk_ports is defined %}
        {% for port_group in trunk_ports %}
        {% for port in port_group['ports'] %}
          {{ port }} {
        {% if 'ae' in port %}
        aggregated-ether-options lacp active;
        {% endif %}
                unit 0 {
            family ethernet-switching {
             {{ switchport_pattern }} trunk;
             {% if port_group['native_vlan'] is defined %} native-vlan-id {{ port_group['native_vlan'] }} ;{% endif %}
             vlan {
               {% set vlan_list = [] %}
               {% if interconnects is defined %}{% if interconnects[port] is defined %}{% set _ = vlan_list.append(interconnects[port])%}{% endif %}{% endif %}
               {% if port_group['vlans'] is defined %}{% for vlan in port_group['vlans'] %}{% set _ = vlan_list.append(vlan) %} {% endfor %}{% endif %}
               {% if port_group['service_groups'] is defined %}{% for local_service_group in port_group['service_groups'] %}{% for vlan_name in service_groups[local_service_group]['networks'] %} {% set _ = vlan_list.append(vlan_name+underlay_id if service_groups[local_service_group]['type'] =='underlay' else vlan_name)%}{% endfor %}{% endfor %}{% endif %}
               members [ {{ vlan_list | join(" ") }}  ]
             }
            }
          }
        }
        {% endfor %}
        {% endfor %}
        {% endif %}
