

- name: closing {{ current_block }}
  blockinfile:
    path: ./config/{{inventory_hostname}}.conf
    marker: ""
    block: |
      {{ oob_port_definition }} {
          unit 0 {
              family inet {
                  address {{network_db['oob-net']['net'] | ipaddr(unit_id) }};
              }
          }
      }
