

- name: fabric_interfaces
  blockinfile:
    path: ./config/{{inventory_hostname}}.conf
    marker: ""
    block: |
      {% if aggregated_ports is defined %}
      {% for port_master,port_slaves in aggregated_ports.items() %}
      {% for slave in port_slaves %}
      {{ slave }} {
        ether-options 802.3ad {{ port_master }};
      }
      {% endfor %}
      {% endfor %}
      {% endif %}
